services:
  node-backend:
    build: .
    container_name: nawam-fabrics-node-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nawam-fabrics
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
  mongo:
    image: mongo
    container_name: nawam-fabrics-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: nawam-fabrics-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/nawam-fabrics
    depends_on:
      - mongo
    restart: unless-stopped
volumes:
  mongo_data:
    driver: local
